version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "spiltcoffee"
    commit-message:
      prefix: "GitHub Actions"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "spiltcoffee"
    commit-message:
      prefix: "NPM"
      prefix-development: "NPM dev"
