version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "spiltcoffee"
    commit-message:
      prefix: "GitHub Actions"
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "spiltcoffee"
    commit-message:
      prefix: "Yarn"
      prefix-development: "Yarn dev"
