export enum ASTType {
  String = "string",
  ControlString = "controlString",
  LiteralString = "literalString",
  BinaryString = "binaryString",
  Integer = "integer",
  HexCode = "hexCode",
  Double = "double",
  Single = "single",
  Currency = "currency",
  DateTime = "dateTime",
  Boolean = "boolean",
  Identifier = "identifier",
  Item = "item",
  VariantList = "variantList",
  BinaryStringList = "binaryStringList",
  IdentifierList = "identifierList",
  ItemList = "itemList",
  Property = "property",
  Object = "object",
  Root = "root"
}
