name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main, beta]
    types:
      - completed

concurrency:
  group: npm

permissions:
  contents: write
  deployments: read
  issues: write
  pull-requests: write

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: npm
      url: https://www.npmjs.com/package/postdfm

    steps:
      - uses: actions/checkout@v4

        # unlike with ci, we only want the latest version to deploy with
      - name: setup node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: latest
          cache: yarn

      - run: yarn install --immutable
      - run: yarn generate
      - run: yarn compile
      - run: yarn release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm config list
      - run: yarn config
