name: Continuous Deployment

concurrency: npm

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main, beta]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/postdfm

    steps:
      - uses: actions/checkout@v2

        # unlike with ci, we only want the latest version to deploy with
      - name: setup node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --immutable
      - run: yarn generate
      - run: yarn compile
      - run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
